name: Windows Matrix Example

on:
  push:

jobs:
  run-matrix:
    runs-on: windows-latest
    strategy:
      matrix:
        instance: [1]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup .NET 10 x86
        uses: actions/setup-dotnet@v4
        continue-on-error: true
        with:
          dotnet-version: '10.0.x'
          dotnet-quality: 'preview'
          cache: true
      - name: Run instance
        run: |
          .\Cheese.LocalServer.exe
